Please run those two cells before running the Notebook!

As those plotting settings are standard throughout the book, we do not show them in the book every time we plot something.

In [1]:
# %matplotlib inline
%config InlineBackend.figure_format = "retina"

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
from pandas.errors import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=FutureWarning)
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

# feel free to modify, for example, change the context to "notebook"
sns.set_theme(context="talk", style="whitegrid", 
              palette="colorblind", color_codes=True, 
              rc={"figure.figsize": [12, 8]})

# Chapter 1 - Acquiring Financial Data

## 1.1 Getting data from Yahoo Finance

### How to do it...

1. Import the libraries:

In [3]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (1.0)
Requirement already satisfied: pandas>=1.3.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (2.3.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: requests>=2.31 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (2.32.5)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (3.19.0)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi<0.14,>=0.7 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (5.29.3)
Requirement already satisfied: websockets>=13.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yfinance) (16.0)
Requirement already satisfied: cffi>=1.12.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from curl_cffi<0.14,>=0.7->yfinance) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: pycparser in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi<0.14,>=0.7->yfinance) (2.23)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.5.0)

In [4]:
import pandas as pd 
import yfinance as yf

2. Download the data:

In [5]:
df = yf.download("AAPL", 
                 start="2011-01-01", 
                 end="2023-12-31",
                 progress=False)

3. Inspect the data:

In [6]:
print(f"Downloaded {len(df)} rows of data.")
df

Downloaded 3270 rows of data.

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2011-01-03    9.884148    9.904842    9.742290    9.766283  445138400
2011-01-04    9.935733    9.972022    9.841560    9.970222  309080800
2011-01-05   10.017009   10.027206    9.882049    9.883549  255519600
2011-01-06   10.008912   10.054498    9.984019   10.038603  300428800
2011-01-07   10.080590   10.087488    9.954028   10.016709  311931200
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243896  192.076034  191.025954  191.798655   28919300
2023-12-27  191.342957  191.689688  189.302232  190.689143   48087700
2023-12-28  191.768951  192.838849  191.362784  192.323710   34049900
2023-12-29  190.728760  192.581260  189.936241  192.085938   42672100

[3270 rows x 5 columns]

### There's more

We can also use the `Ticker` class to download the historical prices and much more.

In [7]:
# instantiate the Ticker class
aapl_data = yf.Ticker("AAPL")

In [8]:
# get the last month of historical prices
aapl_data.history()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-12-22 00:00:00-05:00,272.859985,273.880005,270.510010,270.970001,36571800,0.0,0.0
2025-12-23 00:00:00-05:00,270.839996,272.500000,269.559998,272.359985,29642000,0.0,0.0
2025-12-24 00:00:00-05:00,272.339996,275.429993,272.200012,273.809998,17910600,0.0,0.0
2025-12-26 00:00:00-05:00,274.160004,275.369995,272.859985,273.399994,21521800,0.0,0.0
2025-12-29 00:00:00-05:00,272.690002,274.359985,272.350006,273.760010,23715200,0.0,0.0
2025-12-30 00:00:00-05:00,272.809998,274.079987,272.279999,273.079987,22139600,0.0,0.0
2025-12-31 00:00:00-05:00,273.059998,273.679993,271.750000,271.859985,27293600,0.0,0.0
2026-01-02 00:00:00-05:00,272.260010,277.839996,269.000000,271.010010,37838100,0.0,0.0
2026-01-05 00:00:00-05:00,270.640015,271.510010,266.140015,267.260010,45647200,0.0,0.0
2026-01-06 00:00:00-05:00,267.000000,267.549988,262.119995,262.359985,52352100,0.0,0.0
2026-01-07 00:00:00-05:00,263.200012,263.679993,259.809998,260.329987,48309800,0.0,0.0
2026-01-08 00:00:00-05:00,257.019989,259.290009,255.699997,259.040009,50419300,0.0,0.0
2026-01-09 00:00:00-05:00,259.079987,260.209991,256.220001,259.369995,39997000,0.0,0.0
2026-01-12 00:00:00-05:00,259.160004,261.299988,256.799988,260.250000,45263800,0.0,0.0
2026-01-13 00:00:00-05:00,258.720001,261.809998,258.390015,261.049988,45730800,0.0,0.0
2026-01-14 00:00:00-05:00,259.489990,261.820007,256.709991,259.959991,40019400,0.0,0.0
2026-01-15 00:00:00-05:00,260.649994,261.040009,257.049988,258.209991,39388600,0.0,0.0
2026-01-16 00:00:00-05:00,257.899994,258.899994,254.929993,255.529999,72018600,0.0,0.0
2026-01-20 00:00:00-05:00,252.509995,254.789993,250.850006,251.669998,15967618,0.0,0.0

In [9]:
# get stock's info
aapl_data.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 51,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1768176000,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 255.517,
 'open': 252.51,
 'dayLow': 250.85,
 'dayHigh': 254.79,
 'regularMarketPreviousClose': 255.517,
 'regularMarketOpen': 252.51,
 'regularMarketDayLow': 250.85,
 'regularMarketDayHigh': 254.79,
 'dividendRate': 1.04,
 'dividendYield': 0.41,
 'exDividendDate': 1762732800,
 'payoutRatio': 0.1367,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.093,
 'trailingPE': 33.73725,
 'forwardPE': 27.543356,
 'volume': 10842081,
 'regularMarketVolume': 15968008,
 'averageVolume': 45497947,
 'averageVolume10days': 47914660,
 'averageDailyVolume10Day': 47914660,
 'bid': 250.42,
 'ask': 251.78,
 'bidSize': 2,
 'askSize': 2,
 'marketCap': 3718911098880,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.91067,
 'fiftyDayAverage': 271.5098,
 'twoHundredDayAverage': 234.05525,
 'trailingAnnualDividendRate': 1.02,
 'trailingAnnualDividendYield': 0.0039919065,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3833481396224,
 'profitMargins': 0.26915002,
 'floatShares': 14750346619,
 'sharesOutstanding': 14697926000,
 'sharesShort': 112732788,
 'sharesShortPriorMonth': 129458559,
 'sharesShortPreviousMonthDate': 1764288000,
 'dateShortInterest': 1767139200,
 'sharesPercentSharesOut': 0.0076,
 'heldPercentInsiders': 0.01702,
 'heldPercentInstitutions': 0.64818,
 'shortRatio': 2.68,
 'shortPercentOfFloat': 0.0076,
 'impliedSharesOutstanding': 14776353000,
 'bookValue': 4.991,
 'priceToBook': 50.426746,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1758931200,
 'earningsQuarterlyGrowth': 0.864,
 'netIncomeToCommon': 112010002432,
 'trailingEps': 7.46,
 'forwardEps': 9.13759,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 9.212,
 'enterpriseToEbitda': 26.484,
 '52WeekChange': 0.14772725,
 'SandP52WeekChange': 0.14725316,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1762732800,
 'quoteType': 'EQUITY',
 'currentPrice': 250.96,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 287.21902,
 'targetMedianPrice': 300.0,
 'recommendationMean': 2.0,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 54697000960,
 'totalCashPerShare': 3.702,
 'ebitda': 144748003328,
 'totalDebt': 112377004032,
 'quickRatio': 0.771,
 'currentRatio': 0.893,
 'totalRevenue': 416161005568,
 'debtToEquity': 152.411,
 'revenuePerShare': 27.84,
 'returnOnAssets': 0.22964,
 'returnOnEquity': 1.7142199,
 'grossProfits': 195201007616,
 'freeCashflow': 78862254080,
 'operatingCashflow': 111482003456,
 'earningsGrowth': 0.912,
 'revenueGrowth': 0.079,
 'grossMargins': 0.46905,
 'ebitdaMargins': 0.34782,
 'operatingMargins': 0.31647,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'regularMarketChangePercent': -1.5016993,
 'regularMarketPrice': 251.6799,
 'longName': 'Apple Inc.',
 'corporateActions': [],
 'marketState': 'REGULAR',
 'shortName': 'Apple Inc.',
 'regularMarketTime': 1768925430,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChange': -3.8370972,
 'regularMarketDayRange': '250.85 - 254.79',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 45497947,
 'fiftyTwoWeekLowChange': 82.469894,
 'fiftyTwoWeekLowChangePercent': 0.4873819,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -36.940094,
 'fiftyTwoWeekHighChangePercent': -0.12798868,
 'fiftyTwoWeekChangePercent': 14.772725,
 'dividendDate': 1762992000,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1769720400,
 'earningsTimestampEnd': 1769720400,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.46,
 'epsForward': 9.13759,
 'epsCurrentYear': 8.24255,
 'priceEpsCurrentYear': 30.53423,
 'fiftyDayAverageChange': -19.829895,
 'fiftyDayAverageChangePercent': -0.07303565,
 'twoHundredDayAverageChange': 17.62465,
 'twoHundredDayAverageChangePercent': 0.07530123,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'displayName': 'Apple',
 'trailingPegRatio': 2.5859}

In [10]:
# show corporate actions
aapl_data.actions

                           Dividends  Stock Splits
Date
1987-05-11 00:00:00-04:00   0.000536           0.0
1987-06-16 00:00:00-04:00   0.000000           2.0
1987-08-10 00:00:00-04:00   0.000536           0.0
1987-11-17 00:00:00-05:00   0.000714           0.0
1988-02-12 00:00:00-05:00   0.000714           0.0
...                              ...           ...
2024-11-08 00:00:00-05:00   0.250000           0.0
2025-02-10 00:00:00-05:00   0.250000           0.0
2025-05-12 00:00:00-04:00   0.260000           0.0
2025-08-11 00:00:00-04:00   0.260000           0.0
2025-11-10 00:00:00-05:00   0.260000           0.0

[94 rows x 2 columns]

In [11]:
# show financials
aapl_data.financials

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [12]:
# show quarterly financials
aapl_data.quarterly_financials

,2025-09-30,2025-06-30,2025-03-31,2024-12-31,2024-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.627240e-01,1.640000e-01,1.550000e-01,1.470000e-01,2.100000e-01
Normalized EBITDA,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10,3.250200e+10
Net Income From Continuing Operation Net Minority Interest,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Reconciled Depreciation,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09,2.911000e+09
Reconciled Cost Of Revenue,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10,5.105100e+10
EBITDA,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10,3.250200e+10
EBIT,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10,2.959100e+10
Normalized Income,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Net Income From Continuing And Discontinued Operation,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Total Expenses,7.003900e+10,6.583400e+10,6.577000e+10,8.146800e+10,6.533900e+10
Total Operating Income As Reported,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10,2.959100e+10
Diluted Average Shares,1.486361e+10,1.494818e+10,1.505613e+10,1.515086e+10,1.524285e+10
Basic Average Shares,1.481531e+10,1.490289e+10,1.499408e+10,1.508172e+10,1.517199e+10
Diluted EPS,1.850000e+00,1.570000e+00,1.650000e+00,2.400000e+00,9.700000e-01
Basic EPS,1.850000e+00,1.570000e+00,1.650000e+00,2.410000e+00,9.700000e-01
Diluted NI Availto Com Stockholders,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Net Income Common Stockholders,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Net Income,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Net Income Including Noncontrolling Interests,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Net Income Continuous Operations,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10,1.473600e+10
Tax Provision,5.338000e+09,4.597000e+09,4.530000e+09,6.254000e+09,1.487400e+10
Pretax Income,3.280400e+10,2.803100e+10,2.931000e+10,4.258400e+10,2.961000e+10
Other Income Expense,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08,1.900000e+07
Other Non Operating Income Expenses,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08,1.900000e+07
Operating Income,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10,2.959100e+10
Operating Expense,1.591400e+10,1.551600e+10,1.527800e+10,1.544300e+10,1.428800e+10
Research And Development,8.866000e+09,8.866000e+09,8.550000e+09,8.268000e+09,7.765000e+09
Selling General And Administration,7.048000e+09,6.650000e+09,6.728000e+09,7.175000e+09,6.523000e+09
Gross Profit,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10,4.387900e+10
Cost Of Revenue,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10,5.105100e+10
Total Revenue,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11,9.493000e+10
Operating Revenue,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11,9.493000e+10

In [13]:
# show earnings
aapl_data.earnings

c:\Users\Mario.Chartouni\AppData\Local\anaconda3\Lib\site-packages\yfinance\scrapers\fundamentals.py:33: DeprecationWarning: 'Ticker.earnings' is deprecated as not available via API. Look for "Net Income" in Ticker.income_stmt.
  warnings.warn("'Ticker.earnings' is deprecated as not available via API. Look for \"Net Income\" in Ticker.income_stmt.", DeprecationWarning)

In [14]:
# show quarterly earnings
aapl_data.quarterly_earnings

In [15]:
# show upcoming events, such as earnings
aapl_data.calendar

{'Dividend Date': datetime.date(2025, 11, 13),
 'Ex-Dividend Date': datetime.date(2025, 11, 10),
 'Earnings Date': [datetime.date(2026, 1, 29)],
 'Earnings High': 2.77,
 'Earnings Low': 2.51,
 'Earnings Average': 2.67229,
 'Revenue High': 142741000000,
 'Revenue Low': 136656000000,
 'Revenue Average': 138454776990}

## 1.2 Getting data from Nasdaq Data Link

### How to do it...

1. Import the libraries:

In [16]:
!pip install Quandl

Requirement already satisfied: Quandl in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (3.7.0)
Requirement already satisfied: pandas>=0.14 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (2.3.3)
Requirement already satisfied: numpy>=1.8 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (2.3.5)
Requirement already satisfied: requests>=2.7.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (2.32.5)
Requirement already satisfied: inflection>=0.3.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (0.5.1)
Requirement already satisfied: python-dateutil in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (2.9.0.post0)
Requirement already satisfied: six in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (1.17.0)
Requirement already satisfied: more-itertools in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from Quandl) (10.8.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from pandas>=0.14->Quandl) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from pandas>=0.14->Quandl) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.7.0->Quandl) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.7.0->Quandl) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.7.0->Quandl) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests>=2.7.0->Quandl) (2025.11.12)

In [17]:
import pandas as pd 
import quandl

2. Authenticate using the personal API key: first go to https://data.nasdaq.com and authenticate your email address- then your key will be in your profile:

In [18]:
quandl.ApiConfig.api_key = "KereSx1d5m1yyWDxvSvr"

3. Download the data:

In [22]:
df = yf.download("AAPL", start="2011-01-01", end="2021-12-31")
df.head()

[*********************100%***********************]  1 of 1 completed

Price           Close       High       Low       Open     Volume
Ticker           AAPL       AAPL      AAPL       AAPL       AAPL
Date
2011-01-03   9.884149   9.904842  9.742291   9.766284  445138400
2011-01-04   9.935733   9.972022  9.841560   9.970222  309080800
2011-01-05  10.017008  10.027205  9.882048   9.883548  255519600
2011-01-06  10.008912  10.054498  9.984019  10.038603  300428800
2011-01-07  10.080589  10.087487  9.954027  10.016708  311931200

4. Inspect the data:

In [ ]:
print(f"Downloaded {len(df)} rows of data.")
df.head()

Downloaded 3270 rows of data.

Price           Close       High       Low       Open     Volume
Ticker           AAPL       AAPL      AAPL       AAPL       AAPL
Date
2011-01-03   9.884144   9.904838  9.742287   9.766279  445138400
2011-01-04   9.935736   9.972025  9.841563   9.970225  309080800
2011-01-05  10.017008  10.027205  9.882048   9.883548  255519600
2011-01-06  10.008910  10.054496  9.984017  10.038601  300428800
2011-01-07  10.080590  10.087488  9.954028  10.016709  311931200

### There's more

1. Download the data for multiple tickers using the `get_table` function:

In [ ]:
COLUMNS = ["ticker", "date", "adj_close"]
df = quandl.get_table("WIKI/PRICES", 
                              ticker=["AAPL", "MSFT", "INTC"], 
                              qopts={"columns": COLUMNS}, 
                              date={"gte": "2011-01-01", 
                                    "lte": "2021-12-31"}, 
                              paginate=True)
df.head()

     ticker       date  adj_close
None
0      MSFT 2018-03-27      89.47
1      MSFT 2018-03-26      93.78
2      MSFT 2018-03-23      87.18
3      MSFT 2018-03-22      89.79
4      MSFT 2018-03-21      92.48

2. Pivot the data from long to wide:

In [ ]:
# set the date as index
df = df.set_index("date")

# use the pivot function to reshape the data
df_wide = df.pivot(columns="ticker")
df_wide.head()

            adj_close
ticker           AAPL       INTC       MSFT
date
2011-01-03  42.354338  16.488706  23.211568
2011-01-04  42.575382  16.725954  23.300747
2011-01-05  42.923655  16.559880  23.228159
2011-01-06  42.888956  16.425440  23.908412
2011-01-07  43.196105  16.338449  23.725905

## 1.3 Getting data from Intrinio

### How to do it...

1. Import the libraries:

In [ ]:
!pip install intrinio_sdk
import intrinio_sdk as intrinio
import pandas as pd

Collecting intrinio_sdk
  Downloading intrinio_sdk-6.45.0-py3-none-any.whl.metadata (935 bytes)
Requirement already satisfied: urllib3>=1.15 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from intrinio_sdk) (2.5.0)
Requirement already satisfied: six>=1.10 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from intrinio_sdk) (1.17.0)
Requirement already satisfied: certifi in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from intrinio_sdk) (2025.11.12)
Requirement already satisfied: python-dateutil in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from intrinio_sdk) (2.9.0.post0)
Collecting retrying>=1.3.3 (from intrinio_sdk)
  Downloading retrying-1.4.2-py3-none-any.whl.metadata (5.5 kB)
Downloading intrinio_sdk-6.45.0-py3-none-any.whl (1.2 MB)
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.2 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.2 MB ? eta -:--:--
   -------- ------------------------------- 0.3/1.2 MB ? eta -:--:--
   ----------------- ---------------------- 0.5/1.2 MB 560.2 kB/s eta 0:00:02
   ----------------- ---------------------- 0.5/1.2 MB 560.2 kB/s eta 0:00:02
   ----------------- ---------------------- 0.5/1.2 MB 560.2 kB/s eta 0:00:02
   ------------------------- -------------- 0.8/1.2 MB 440.8 kB/s eta 0:00:02
   ------------------------- -------------- 0.8/1.2 MB 440.8 kB/s eta 0:00:02
   ------------------------- -------------- 0.8/1.2 MB 440.8 kB/s eta 0:00:02
   ---------------------------------- ----- 1.0/1.2 MB 455.4 kB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 482.0 kB/s  0:00:02
Downloading retrying-1.4.2-py3-none-any.whl (10 kB)
Installing collected packages: retrying, intrinio_sdk

   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   -------------------- ------------------- 1/2 [intrinio_sdk]
   ---------------------------------------- 2/2 [intrinio_sdk]

Successfully installed intrinio_sdk-6.45.0 retrying-1.4.2

2. Authenticate using the personal API key and select the API:

In [ ]:
intrinio.ApiClient().set_api_key("YOUR_KEY_HERE") 
security_api = intrinio.SecurityApi()

3. Request the data:

In [ ]:
r = security_api.get_security_stock_prices(
    identifier="AAPL", 
    start_date="2011-01-01",
    end_date="2021-12-31", 
    frequency="daily",
    page_size=10000
)

4. Convert the results into a DataFrame:

In [ ]:
df = (
    pd.DataFrame(r.stock_prices_dict)
    .sort_values("date")
    .set_index("date")
)

5. Inspect the data:

In [ ]:
print(f"Downloaded {df.shape[0]} rows of data.")

df.head()

Downloaded 2675 rows of data.

,intraperiod,frequency,open,high,low,close,volume,adj_open,adj_high,adj_low,adj_close,adj_volume,factor,split_ratio,dividend,change,percent_change,fifty_two_week_high,fifty_two_week_low
date,,,,,,,,,,,,,,,,,,,
2011-01-03,False,daily,325.90,330.26,324.8365,329.57,15897201.0,9.993683,10.127381,9.961070,10.106223,445121628.0,1.0,1.0,0.0,0.21,0.0217,10.13,5.83
2011-01-04,False,daily,332.50,332.50,328.1500,331.29,11048143.0,10.196071,10.196071,10.062679,10.158966,309348004.0,1.0,1.0,0.0,0.05,0.0052,10.20,5.83
2011-01-05,False,daily,329.55,334.34,329.5000,334.00,9125599.0,10.105609,10.252494,10.104076,10.242068,255516772.0,1.0,1.0,0.0,0.08,0.0082,10.25,5.83
2011-01-06,False,daily,335.00,335.25,332.9000,333.73,10729518.0,10.272733,10.280399,10.208337,10.233789,300426504.0,1.0,1.0,0.0,-0.01,-0.0008,10.28,5.83
2011-01-07,False,daily,334.12,336.35,331.9000,336.12,11140316.0,10.245748,10.314130,10.177672,10.307078,311928848.0,1.0,1.0,0.0,0.07,0.0072,10.31,5.83

### There's more

1. Get Coca-Cola's real-time stock price:

In [ ]:
security_api.get_security_realtime_price("KO")

{'ask_price': 68.0,
 'ask_size': 1.0,
 'bid_price': 64.0,
 'bid_size': 1.0,
 'close_price': None,
 'exchange_volume': 1527525.0,
 'high_price': 67.03,
 'last_price': 66.1,
 'last_size': None,
 'last_time': datetime.datetime(2022, 4, 25, 22, 6, 17, tzinfo=tzutc()),
 'low_price': 48.13,
 'market_volume': None,
 'open_price': 66.5,
 'security': {'composite_figi': 'BBG000BMX289',
              'exchange_ticker': 'KO:UN',
              'figi': 'BBG000BMX4N8',
              'id': 'sec_X7m9Zy',
              'ticker': 'KO'},
 'source': 'bats_delayed',
 'updated_on': datetime.datetime(2022, 4, 25, 22, 21, 20, 659000, tzinfo=tzutc())}

2. Download news articles related to Coca-Cola:

In [ ]:
r = intrinio.CompanyApi().get_company_news(
    identifier="KO", 
    page_size=100
)

df = pd.DataFrame(r.news_dict)
df.head()

,id,title,publication_date,url,summary
0,nws_1ExBnx,12 Best Blue-Chip Stocks Right Now,2021-08-09 20:27:39+00:00,https://finance.yahoo.com/news/12-best-blue-ch...,"In this article, we will look at the 12 best b..."
1,nws_JbL8mV,The Coca-Cola Company (NYSE:KO) Yields 3% With...,2021-08-09 09:26:07+00:00,https://finance.yahoo.com/news/coca-cola-compa...,The Coca-Cola Company NYSE:KO) is a staple sto...
2,nws_DkAPKO,10 High Yield Monthly Dividend Stocks to Buy i...,2021-08-07 13:57:00+00:00,https://finance.yahoo.com/news/10-high-yield-m...,"In this article, we will be looking at 10 high..."
3,nws_pRYkD9,10 Best Dividend Paying Stocks to Buy Now,2021-08-04 14:32:49+00:00,https://finance.yahoo.com/news/10-best-dividen...,"In this article, we will be looking at the 10 ..."
4,nws_kpVJDP,PepsiCo (PEP) Agrees to Offload Its Juice Bran...,2021-08-04 13:21:01+00:00,https://finance.yahoo.com/news/pepsico-pep-agr...,PepsiCo (PEP) unveils plans to offload juice b...

3. Search for companies connected to the search phrase:

Returns a list of companies recognized by the Thea API in the given `text` query string parameter.

In [ ]:
r = intrinio.CompanyApi().recognize_company("Intel")
df = pd.DataFrame(r.companies_dict)
df

4. Get Coca-Cola's intraday stock prices:

In [ ]:
response = (
    security_api.get_security_intraday_prices(identifier="KO", 
                                              start_date="2021-01-02",
                                              end_date="2021-01-05",
                                              page_size=1000)
    )
df = pd.DataFrame(response.intraday_prices_dict)
df

,time,last_price,ask_price,ask_size,bid_price,bid_size,volume,source
0,2021-01-04 20:59:58+00:00,52.755,55.00,100.0,52.30,234.0,0.0,None
1,2021-01-04 20:59:57+00:00,52.745,55.00,100.0,52.74,200.0,870885.0,None
2,2021-01-04 20:59:54+00:00,52.745,55.00,100.0,52.30,234.0,870641.0,None
3,2021-01-04 20:59:51+00:00,52.740,55.00,100.0,52.30,234.0,870341.0,None
4,2021-01-04 20:59:49+00:00,52.725,52.73,600.0,52.71,300.0,868833.0,None
...,...,...,...,...,...,...,...,...
995,2021-01-04 19:01:07+00:00,52.490,52.50,100.0,52.48,200.0,582993.0,None
996,2021-01-04 19:01:03+00:00,52.510,52.50,200.0,52.49,200.0,582493.0,None
997,2021-01-04 19:01:02+00:00,52.495,52.51,200.0,52.49,200.0,582093.0,None
998,2021-01-04 19:00:59+00:00,52.510,52.51,200.0,52.50,200.0,580893.0,None
999,2021-01-04 19:00:51+00:00,52.505,52.51,200.0,52.50,100.0,580793.0,None

5. Get Coca-Cola's latest earnings record:

In [ ]:
r = security_api.get_security_latest_earnings_record(identifier="KO")
print(r)

{'board_of_directors_meeting_date': None,
 'board_of_directors_meeting_type': None,
 'broadcast_url': 'http://mmm.wallstreethorizon.com/u.asp?u=347366',
 'company_website': 'http://mmm.wallstreethorizon.com/u.asp?u=14711',
 'conference_call_date': datetime.date(2020, 10, 22),
 'conference_call_passcode': None,
 'conference_call_phone_number': None,
 'conference_call_time': '8:30 AM',
 'last_confirmation_date': datetime.date(2020, 9, 23),
 'next_earnings_date': datetime.date(2020, 10, 22),
 'next_earnings_fiscal_year': 2020,
 'next_earnings_quarter': 'Q3',
 'preliminary_earnings_date': None,
 'q1_date': datetime.date(2020, 4, 21),
 'q2_date': datetime.date(2020, 7, 21),
 'q3_date': datetime.date(2020, 10, 22),
 'q4_date': datetime.date(2020, 1, 30),
 'quarter': 'Q3',
 'security': {'code': 'EQS',
              'company_id': 'com_VXWJgv',
              'composite_figi': 'BBG000BMX289',
              'composite_ticker': 'KO:US',
              'currency': 'USD',
              'figi': 'BBG000BMX4N8',
              'id': 'sec_X7m9Zy',
              'name': 'Coca-Cola Co',
              'primary_listing': True,
              'share_class_figi': 'BBG001S5SMQ8',
              'ticker': 'KO'},
 'time_of_day': 'Before Market',
 'transcript_fiscal_year': None,
 'transcript_quarter': None,
 'transcript_url': None,
 'type': 'V'}

## 1.4 Getting data from Alpha Vantage

### How to do it...

1. Import the libraries:

In [ ]:
!pip install alpha_vantage
from alpha_vantage.cryptocurrencies import CryptoCurrencies

Collecting alpha_vantage
  Downloading alpha_vantage-3.0.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: aiohttp in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from alpha_vantage) (3.13.2)
Requirement already satisfied: requests in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from alpha_vantage) (2.32.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from aiohttp->alpha_vantage) (1.22.0)
Requirement already satisfied: idna>=2.0 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from yarl<2.0,>=1.17.0->aiohttp->alpha_vantage) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->alpha_vantage) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->alpha_vantage) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->alpha_vantage) (2025.11.12)
Downloading alpha_vantage-3.0.0-py3-none-any.whl (35 kB)
Installing collected packages: alpha_vantage
Successfully installed alpha_vantage-3.0.0

2. Authenticate using the personal API key and select the API:

In [ ]:
ALPHA_VANTAGE_API_KEY = "YOUR_KEY_HERE"

crypto_api = CryptoCurrencies(key=ALPHA_VANTAGE_API_KEY, 
                              output_format="pandas")

3. Download the daily prices of Bitcoin, expressed in EUR:

In [ ]:
data, meta_data = crypto_api.get_digital_currency_daily(
    symbol="BTC", 
    market="EUR"
)

In [ ]:
meta_data

{'1. Information': 'Daily Prices and Volumes for Digital Currency',
 '2. Digital Currency Code': 'BTC',
 '3. Digital Currency Name': 'Bitcoin',
 '4. Market Code': 'EUR',
 '5. Market Name': 'Euro',
 '6. Last Refreshed': '2022-04-25 00:00:00',
 '7. Time Zone': 'UTC'}

In [ ]:
data

,1a. open (EUR),1b. open (USD),2a. high (EUR),2b. high (USD),3a. low (EUR),3b. low (USD),4a. close (EUR),4b. close (USD),5. volume,6. market cap (USD)
date,,,,,,,,,,
2022-04-25,36491.36100,39450.12,36538.27700,39500.84,35870.45475,38778.87,36130.50000,39060.00,3032.078540,3032.078540
2022-04-24,36483.48925,39441.61,36944.50000,39940.00,36009.89850,38929.62,36491.37025,39450.13,26703.611860,26703.611860
2022-04-23,36731.00075,39709.19,36981.50000,39980.00,36338.62500,39285.00,36483.48000,39441.60,20291.423750,20291.423750
2022-04-22,37444.00925,40480.01,37735.43050,40795.06,36238.72500,39177.00,36730.99150,39709.18,46664.019600,46664.019600
2022-04-21,38256.32575,41358.19,39752.80000,42976.00,36769.67500,39751.00,37444.00925,40480.01,59316.276570,59316.276570
...,...,...,...,...,...,...,...,...,...,...
2019-08-04,10005.59550,10816.86,10212.00000,11040.00,9760.60000,10552.00,10109.53775,10929.23,39924.745141,39924.745141
2019-08-03,9734.46875,10523.75,10086.91225,10904.77,9710.58525,10497.93,10005.59550,10816.86,33802.318824,33802.318824
2019-08-02,9596.87500,10375.00,9869.75000,10670.00,9510.24875,10281.35,9734.46875,10523.75,42990.444221,42990.444221
2019-08-01,9324.49025,10080.53,9682.77050,10467.86,9123.70050,9863.46,9596.86575,10374.99,41727.637028,41727.637028
2019-07-31,8856.87500,9575.00,9351.56500,10109.80,8838.37500,9555.00,9324.49025,10080.53,39515.354560,39515.354560

4. Download the realtime exchange rate:

In [ ]:
crypto_api.get_digital_currency_exchange_rate(
    from_currency="BTC", 
    to_currency="USD"
)[0].transpose()

                      Realtime Currency Exchange Rate
1. From_Currency Code                             BTC
2. From_Currency Name                         Bitcoin
3. To_Currency Code                               USD
4. To_Currency Name              United States Dollar
5. Exchange Rate                       22480.74000000
6. Last Refreshed                 2022-08-04 19:58:01
7. Time Zone                                      UTC
8. Bid Price                           22480.76000000
9. Ask Price                           22481.69000000

### There's more

1. Import the libraries:

In [ ]:
import requests
import pandas as pd
from io import BytesIO

2. Download Bitcoin's intraday data:

In [ ]:
AV_API_URL = "https://www.alphavantage.co/query"
parameters = {
    "function": "CRYPTO_INTRADAY",
    "symbol": "ETH",
    "market": "USD",
    "interval": "30min",
    "outputsize": "full",
    "apikey": ALPHA_VANTAGE_API_KEY
}
r = requests.get(AV_API_URL, params=parameters)
data = r.json()
df = (
    pd.DataFrame(data["Time Series Crypto (30min)"])
    .transpose()
)
df

NameError: name 'ALPHA_VANTAGE_API_KEY' is not defined

3. Download the upcoming earnings announcements:

In [ ]:
AV_API_URL = "https://www.alphavantage.co/query" 
parameters = {
    "function": "EARNINGS_CALENDAR",
    "horizon": "3month",
    "apikey": ALPHA_VANTAGE_API_KEY
}

r = requests.get(AV_API_URL, params=parameters)
pd.read_csv(BytesIO(r.content))

,symbol,name,reportDate,fiscalDateEnding,estimate,currency
0,A,Agilent Technologies Inc,2022-05-23,2022-04-30,1.12,USD
1,AA,Alcoa Corp,2022-07-13,2022-06-30,3.56,USD
2,AACG,ATA Creativity Global,2022-05-11,2022-03-31,-0.25,CNY
3,AADI,Aadi Bioscience Inc,2022-05-16,2022-03-31,-0.71,USD
4,AAIC,Arlington Asset Investment Corp - Class A,2022-05-04,2022-03-31,0.03,USD
...,...,...,...,...,...,...
5308,ZWS,Zurn Water Solutions Corp,2022-04-26,2022-03-31,0.22,USD
5309,ZY,Zymergen Inc,2022-05-12,2022-03-31,-0.71,USD
5310,ZYME,Zymeworks Inc,2022-05-04,2022-03-31,-1.63,USD
5311,ZYNE,Zynerba Pharmaceuticals Inc,2022-05-10,2022-03-31,-0.23,USD
5312,ZYXI,Zynex Inc,2022-04-28,2022-03-31,0.05,USD

In [ ]:
type(r.content)

bytes

### Bonus

This section includes some additional short recipes not published in the book.

1. Get Tesla's earnings:

In [ ]:
AV_API_URL = "https://www.alphavantage.co/query" 
parameters = {
    "function": "EARNINGS",
    "symbol": "TSLA", 
    "apikey": ALPHA_VANTAGE_API_KEY
}
r = requests.get(AV_API_URL,  params=parameters)
data = r.json()

In [ ]:
data.keys()

dict_keys(['symbol', 'annualEarnings', 'quarterlyEarnings'])

In [ ]:
df = pd.DataFrame(data["quarterlyEarnings"])
df.head()

,fiscalDateEnding,reportedDate,reportedEPS,estimatedEPS,surprise,surprisePercentage
0,2022-03-31,2022-04-20,3.22,2.26,0.96,42.4779
1,2021-12-31,2022-01-26,2.54,2.37,0.17,7.173
2,2021-09-30,2021-10-20,1.86,1.6143,0.2457,15.2202
3,2021-06-30,2021-07-26,1.45,0.9789,0.4711,48.1254
4,2021-03-31,2021-04-26,0.93,0.7787,0.1513,19.4298

2. Download the upcoming IPOs:

In [ ]:
import csv

AV_API_URL = "https://www.alphavantage.co/query" 
parameters = {
    "function": "IPO_CALENDAR",
    "apikey": ALPHA_VANTAGE_API_KEY
}

with requests.Session() as s:
    download = s.get(AV_API_URL, params=parameters)
    decoded_content = download.content.decode("utf-8")
    ipos_list = list(csv.reader(decoded_content.splitlines(), delimiter=","))

df = pd.DataFrame(ipos_list[1:], columns=ipos_list[0])
df

Empty DataFrame
Columns: [{}]
Index: []

3. Download Google's stock prices using the `TimeSeries` module:

In [ ]:
from alpha_vantage.timeseries import TimeSeries

ts = TimeSeries(key=ALPHA_VANTAGE_API_KEY, output_format="pandas")
data, _ = ts.get_daily("GOOGL", outputsize="full")
print(f"Downloaded {len(data)} observations")
data

Downloaded 4452 observations

            1. open  2. high   3. low  4. close   5. volume
date
2022-04-25  2382.02  2465.55  2370.22  2461.480   2293404.0
2022-04-22  2500.00  2508.04  2378.50  2392.710   2844186.0
2022-04-21  2585.00  2601.97  2490.53  2496.290   1822258.0
2022-04-20  2617.84  2627.98  2550.00  2560.800   1573067.0
2022-04-19  2553.83  2606.66  2539.99  2600.180   1324488.0
...             ...      ...      ...       ...         ...
2004-08-25   104.76   108.00   103.88   106.000   9188600.0
2004-08-24   111.24   111.60   103.57   104.870  15247300.0
2004-08-23   110.76   113.48   109.05   109.400  18256100.0
2004-08-20   101.01   109.08   100.50   108.310  22834300.0
2004-08-19   100.01   104.06    95.96   100.335  44659000.0

[4452 rows x 5 columns]

4. Similarly, we can download the intraday prices:

In [ ]:
data, _ = ts.get_intraday("GOOGL", interval="5min", outputsize="full")
data

                       1. open    2. high     3. low   4. close  5. volume
date
2022-04-22 19:30:00  2388.0000  2388.0000  2388.0000  2388.0000      205.0
2022-04-22 18:05:00  2388.0000  2388.0000  2388.0000  2388.0000      210.0
2022-04-22 18:00:00  2389.2300  2389.2300  2389.2300  2389.2300      475.0
2022-04-22 17:55:00  2389.0644  2389.0644  2389.0644  2389.0644      299.0
2022-04-22 17:45:00  2389.0000  2389.0000  2389.0000  2389.0000      129.0
...                        ...        ...        ...        ...        ...
2022-03-28 08:15:00  2835.9000  2835.9000  2835.9000  2835.9000      960.0
2022-03-28 08:05:00  2836.3572  2836.3572  2835.0000  2835.0000    15340.0
2022-03-28 07:35:00  2835.0000  2835.0000  2835.0000  2835.0000      696.0
2022-03-28 07:15:00  2833.1700  2833.1700  2833.1700  2833.1700      265.0
2022-03-28 07:05:00  2836.7900  2836.7900  2836.7900  2836.7900      102.0

[1836 rows x 5 columns]

## 1.5 Getting data from CoinGecko

### How to do it...

1. Import the libraries:

In [24]:
%pip install pycoingecko

Collecting pycoingecko
  Downloading pycoingecko-3.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: requests in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from pycoingecko) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->pycoingecko) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->pycoingecko) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->pycoingecko) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mario.chartouni\appdata\local\anaconda3\lib\site-packages (from requests->pycoingecko) (2025.11.12)
Downloading pycoingecko-3.2.0-py3-none-any.whl (10 kB)
Installing collected packages: pycoingecko
Successfully installed pycoingecko-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [25]:
from pycoingecko import CoinGeckoAPI
from datetime import datetime
import pandas as pd

2. Instantiate the CoinGecko API:

In [26]:
cg = CoinGeckoAPI()

3. Get Bitcoin's OHLC prices from the last 14 days:

In [27]:
ohlc = cg.get_coin_ohlc_by_id(
    id="bitcoin", vs_currency="usd", days="14"
)
ohlc_df = pd.DataFrame(ohlc)
ohlc_df.columns = ["date", "open", "high", "low", "close"]
ohlc_df["date"] = pd.to_datetime(ohlc_df["date"], unit="ms")
ohlc_df

                  date     open     high      low    close
0  2026-01-06 20:00:00  93649.0  93668.0  91545.0  92011.0
1  2026-01-07 00:00:00  92064.0  93667.0  92064.0  93667.0
2  2026-01-07 04:00:00  93647.0  93647.0  92353.0  92756.0
3  2026-01-07 08:00:00  92754.0  92805.0  92479.0  92758.0
4  2026-01-07 12:00:00  92820.0  92847.0  91570.0  92091.0
..                 ...      ...      ...      ...      ...
79 2026-01-20 00:00:00  93106.0  93208.0  92325.0  92558.0
80 2026-01-20 04:00:00  92559.0  92771.0  92247.0  92358.0
81 2026-01-20 08:00:00  92366.0  92383.0  90766.0  91140.0
82 2026-01-20 12:00:00  91061.0  91320.0  90678.0  91169.0
83 2026-01-20 16:00:00  91132.0  91201.0  89930.0  90345.0

[84 rows x 5 columns]

### There's more

1. Get the top 7 trending coins (based on the # of searches in the last 24h) from CoinGecko:

In [28]:
trending_coins = cg.get_search_trending()
(
    pd.DataFrame([coin["item"] for coin in trending_coins["coins"]])
    .drop(columns=["thumb", "small", "large"])
)

,id,coin_id,name,symbol,market_cap_rank,slug,price_btc,score,data
0,bitcoin,1,Bitcoin,BTC,1,bitcoin,1.000000e+00,0,"{'price': 90828.07969723131, 'price_btc': '1.0..."
1,aia,69053,DeAgentAI,AIA,890,deagentai,3.510669e-06,1,"{'price': 0.31877054432748647, 'price_btc': '0..."
2,axie-infinity,13029,Axie Infinity,AXS,202,axie-infinity,2.232224e-05,2,"{'price': 2.0268704177789294, 'price_btc': '0...."
3,hyperliquid,50882,Hyperliquid,HYPE,32,hyperliquid,2.430455e-04,3,"{'price': 22.06865741762933, 'price_btc': '0.0..."
4,the-sandbox,12129,The Sandbox,SAND,182,the-sandbox,1.587088e-06,4,"{'price': 0.14410836293344537, 'price_btc': '0..."
5,solana,4128,Solana,SOL,7,solana,1.411385e-03,5,"{'price': 128.17152469969977, 'price_btc': '0...."
6,lighter,71121,Lighter,LIT,175,lighter,1.795405e-05,6,"{'price': 1.6302373163908208, 'price_btc': '0...."
7,elsa,71623,Elsa,ELSA,943,elsa,1.397284e-06,7,"{'price': 0.12687408870758227, 'price_btc': '0..."
8,pudgy-penguins,52622,Pudgy Penguins,PENGU,132,pudgy-penguins,1.100188e-07,8,"{'price': 0.009989761353150287, 'price_btc': '..."
9,monad,38927,Monad,MON,280,monad,2.048517e-07,9,"{'price': 0.0186006360927016, 'price_btc': '0...."
10,monero,69,Monero,XMR,18,monero,5.952666e-03,10,"{'price': 540.5051256246562, 'price_btc': '0.0..."
11,bittensor,28452,Bittensor,TAO,53,bittensor,2.630372e-03,11,"{'price': 238.87089647599797, 'price_btc': '0...."
12,ethereum,279,Ethereum,ETH,2,ethereum,3.342462e-02,12,"{'price': 3034.9726488038314, 'price_btc': '0...."
13,berachain-bera,25235,Berachain,BERA,360,berachain,1.003298e-05,13,"{'price': 0.9109998291674908, 'price_btc': '0...."
14,zcash,486,Zcash,ZEC,28,zcash,3.942639e-03,14,"{'price': 357.9936295434151, 'price_btc': '0.0..."

2. Get Bitcoin's current price in USD:

In [29]:
cg.get_price(ids="bitcoin", vs_currencies="usd")

{'bitcoin': {'usd': 90545}}

### Bonus

This section includes some additional short recipes not published in the book.

1. Get current price of ETH and BTC in USD and EUR:

In [30]:
cg.get_price(ids=["bitcoin", "ethereum"], vs_currencies=["usd", "eur"])

{'bitcoin': {'usd': 90525, 'eur': 77152},
 'ethereum': {'usd': 3023.69, 'eur': 2576.99}}

2. Get the current BTC/USD eschange rate, market capitalization, 24h volumne and change and the last-updated timestamp:

In [31]:
cg.get_price(ids="bitcoin", vs_currencies="usd", 
             include_market_cap=True, 
             include_24hr_vol=True, 
             include_24hr_change=True, 
             include_last_updated_at=True)

{'bitcoin': {'usd': 90520,
  'usd_market_cap': 1812784852681.8896,
  'usd_24h_vol': 47999866098.532875,
  'usd_24h_change': -2.7473809876924764,
  'last_updated_at': 1768926422}}

3. Get the list of all supported coin ids, together with their name and symbol:

In [ ]:
pd.DataFrame(cg.get_coins_list())

,id,symbol,name
0,01coin,zoc,01coin
1,0-5x-long-algorand-token,algohalf,0.5X Long Algorand Token
2,0-5x-long-altcoin-index-token,althalf,0.5X Long Altcoin Index Token
3,0-5x-long-ascendex-token-token,asdhalf,0.5X Long AscendEx Token Token
4,0-5x-long-bitcoin-cash-token,bchhalf,0.5X Long Bitcoin Cash Token
...,...,...,...
13685,zyro,zyro,Zyro
13686,zyrri,zyr,Zyrri
13687,zytara-dollar,zusd,Zytara Dollar
13688,zyx,zyx,ZYX
13689,zzz-finance-v2,zzzv2,zzz.finance v2

4. Get all the coins market data:

In [ ]:
pd.DataFrame(cg.get_coins_markets(vs_currency="eur"))

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://assets.coingecko.com/coins/images/1/la...,37572.000000,714522335039,1,7.888125e+11,3.001232e+10,37632.000000,...,2.100000e+07,2.100000e+07,59717.000000,-37.09896,2021-11-10T14:24:11.849Z,51.300000,7.312353e+04,2013-07-05T00:00:00.000Z,None,2022-04-25T22:23:01.418Z
1,ethereum,eth,Ethereum,https://assets.coingecko.com/coins/images/279/...,2812.020000,338633922241,2,NaN,2.041017e+10,2817.950000,...,NaN,NaN,4228.930000,-33.56248,2021-12-01T08:38:24.623Z,0.381455,7.364466e+05,2015-10-20T00:00:00.000Z,"{'times': 99.10665754233172, 'currency': 'btc'...",2022-04-25T22:23:21.429Z
2,tether,usdt,Tether,https://assets.coingecko.com/coins/images/325/...,0.933983,77646207939,3,NaN,6.063136e+10,0.937355,...,8.312620e+10,NaN,1.130000,-17.45525,2018-07-24T00:00:00.000Z,0.533096,7.521739e+01,2015-03-02T00:00:00.000Z,None,2022-04-25T22:23:17.284Z
3,binancecoin,bnb,BNB,https://assets.coingecko.com/coins/images/825/...,376.660000,63318435510,4,6.331844e+10,1.942997e+09,376.590000,...,1.681370e+08,1.681370e+08,583.170000,-35.42436,2021-11-26T02:58:28.000Z,0.033599,1.120718e+06,2017-10-19T00:00:00.000Z,None,2022-04-25T22:24:06.328Z
4,usd-coin,usdc,USD Coin,https://assets.coingecko.com/coins/images/6319...,0.933715,46585230803,5,NaN,5.108815e+09,0.940757,...,4.989235e+10,NaN,1.048000,-10.89265,2019-05-08T00:40:28.300Z,0.730265,2.785979e+01,2021-05-19T13:14:05.611Z,None,2022-04-25T22:23:49.388Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,curve-dao-token,crv,Curve DAO Token,https://assets.coingecko.com/coins/images/1212...,2.550000,1000747435,96,8.433297e+09,2.445880e+08,2.580000,...,1.734036e+09,3.303030e+09,45.710000,-94.41294,2020-08-14T04:53:44.010Z,0.279972,8.121684e+02,2020-11-05T13:09:50.181Z,None,2022-04-25T22:24:10.774Z
96,dash,dash,Dash,https://assets.coingecko.com/coins/images/19/l...,92.670000,991075201,97,NaN,1.456325e+08,93.440000,...,1.892000e+07,NaN,1257.390000,-92.62767,2017-12-20T00:00:00.000Z,0.163048,5.675401e+04,2014-02-14T00:00:00.000Z,None,2022-04-25T22:25:21.188Z
97,mina-protocol,mina,Mina Protocol,https://assets.coingecko.com/coins/images/1562...,2.080000,986106196,98,NaN,4.869614e+07,2.110000,...,9.122704e+08,NaN,7.430000,-72.06197,2021-06-01T01:42:37.064Z,0.786237,1.640692e+02,2021-07-21T02:30:02.124Z,None,2022-04-25T22:24:12.030Z
98,amp-token,amp,Amp,https://assets.coingecko.com/coins/images/1240...,0.020194,970112051,99,2.004825e+09,2.990071e+07,0.021637,...,9.944384e+10,9.922516e+10,0.099698,-79.74358,2021-06-16T16:03:41.147Z,0.002138,8.447712e+02,2020-11-04T13:18:12.191Z,None,2022-04-25T22:24:24.243Z
99,lido-dao,ldo,Lido DAO,https://assets.coingecko.com/coins/images/1357...,3.060000,958244654,100,3.070086e+09,6.280524e+06,3.090000,...,9.963085e+08,1.000000e+09,6.250000,-51.06299,2021-08-20T08:35:20.158Z,0.427263,6.163696e+02,2021-03-23T06:56:59.032Z,None,2022-04-25T22:24:53.035Z

5. Get all the supported crypto exchanges:

In [ ]:
exchanges_df = pd.DataFrame(cg.get_exchanges_list(per_page=250))
exchanges_df.head()

,id,name,year_established,country,description,url,image,has_trading_incentive,trust_score,trust_score_rank,trade_volume_24h_btc,trade_volume_24h_btc_normalized
0,binance,Binance,2017.0,Cayman Islands,,https://www.binance.com/,https://assets.coingecko.com/markets/images/52...,False,10.0,1.0,460962.137271,460962.137271
1,okex,OKX,2013.0,Belize,,https://www.okx.com,https://assets.coingecko.com/markets/images/96...,False,10.0,2.0,96523.691151,96523.691151
2,gdax,Coinbase Exchange,2012.0,United States,,https://www.coinbase.com,https://assets.coingecko.com/markets/images/23...,False,10.0,3.0,81675.659788,81675.659788
3,kucoin,KuCoin,2014.0,Seychelles,,https://www.kucoin.com/,https://assets.coingecko.com/markets/images/61...,False,10.0,4.0,70408.647942,70408.647942
4,gate,Gate.io,NaN,Hong Kong,"Gate was established in 2013, and it is the to...",https://gate.io/,https://assets.coingecko.com/markets/images/60...,False,10.0,5.0,62150.726708,62150.726708

6. Get a summary of DEFI:

In [ ]:
cg.get_global_decentralized_finance_defi()

{'defi_market_cap': '118949637319.874721498878154217',
 'eth_market_cap': '362878286359.5266097022944933676',
 'defi_to_eth_ratio': '32.7794860676848949187041412290563546987479655139292506626907626',
 'trading_volume_24h': '8086105196.01992223011241297138',
 'defi_dominance': '6.0673547283151764961090911610960009692607355347723013',
 'top_coin_name': 'Terra',
 'top_coin_defi_dominance': 27.92948814210331}